### ISSUE TITLE
Error setting poster for a collection

### ISSUE THREAD

**Issue by coding-blip** [jonjonsson/Emby-MDBList-Collection-Creator#11]
It seems that the collection is created properly and items are added to it as expected, but I get the below error in my logs. I originally thought it was because I had manually updated the poster for the collection previously so I completely deleted the collection and re-tried.

```
Collection Christmas does not exist. Will create it.

=========================================
Processing Christmas. List has 3601 IMDB IDs
.........................................................................
Added 116 new items and removed 0
Successfully created collection Christmas
Processing Christmas with 'add' in 3 batches
...
Traceback (most recent call last):
  File "/app/app.py", line 365, in <module>
    main()
    ~~~~^^
  File "/app/app.py", line 324, in main
    process_my_lists_on_mdblist()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/app/app.py", line 216, in process_my_lists_on_mdblist
    process_list(mdblist_list)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^
    collection_name = mdblist_list["name"]
                      ~~~~~~~~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'
Finished 'add' with 115 items in Christmas
Error setting image for item 48108, response: <Response [500]>
Failed to set poster for Christmas.
Updated item 48108 with {'ForcedSortName': '!39498014 Christmas'}. Waiting 1 seconds.
Updated sort name for Christmas to !39498014 Christmas
=========================================
```

This is what I have for my config of the collection in the `config.cfg` file:
```
[Christmas]
source = https://mdblist.com/lists/cyberoxide/christmas
poster = https://www.publicdomainpictures.net/pictures/280000/velka/vintage-christmas-poster-15419982339El.jpg
frequency = 100
update_items_sort_names = False
```

Semi-related and possibly same issue as I got the same error I am seeing above, would it be possible to get an example of how to use a local file path for the posters? I tried the following line to mount a "posters" dir in the docker container: 
```
- ${CONFIG_DIR}/emby-collections/posters:/posters
```
and then set the following in my config for the Christmas collection
```
poster = /posters/poster-name.ext
```

**Comment by cj0r** [comment]
Confirmed, I get the same errors:

```
Exception occurred while uploading image: Failed to parse: .....
Failed to set poster for......
```

**Comment by coding-blip** [comment]
Bump on this as I am still seeing this issue in my logs. Thank you!

**Comment by jonjonsson** [comment]
I can contribute help if this is due to a problem with the script and not related to a container.  I don't have container expertise on mounting files etc.
