### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by ntls2000** [jonjonsson/Emby-MDBList-Collection-Creator#2]
Hi, i'm testing your script

I have error :

Collection Trending Movies does not exist. Will create it.

=========================================
Traceback (most recent call last):
  File "app.py", line 249, in <module>
    main()
  File "app.py", line 226, in main
    process_hardcoded_lists()
  File "app.py", line 209, in process_hardcoded_lists
    process_list(mdblist_list)
  File "app.py", line 94, in process_list
    mdblist_imdb_ids = mdblist.get_list(list_id)
  File "/volume1/docker/emby/script/Emby/mdblist.py", line 30, in get_list
    imdb_ids = [item["imdb_id"] for item in list]
  File "/volume1/docker/emby/script/Emby/mdblist.py", line 30, in <listcomp>
    imdb_ids = [item["imdb_id"] for item in list]
TypeError: string indices must be integers

**Comment by ntls2000** [comment]
Sorry, i have test with config sample for imdb id, it's ok

Works very well, good job
